repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.0.3
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/wbreza/presidio-hook
    rev: 0.0.4
    hooks:
      - id: presidio
        args: ["--config", "./presidio.yaml"]
