name: Scan Code for Secrets

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  check-for-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with: 
          python-version: 3.8.0
      - name: Install Dependencies
        run: pip install detect-secrets==1.0.3 pyahocorasick
      - name: Detect Secrets against known baseline with wordlist
        run: git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline --word-list secrets-wordlist.txt
